spring:

  jackson:
    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: true
    serialization:
      order-map-entries-by-keys: true
      fail-on-empty-beans: false

  data:
    rest:
      base-path: api
      detection-strategy: annotated
      return-body-on-create: false
      return-body-on-update: false

  datasource:
    url: jdbc:h2:file:./data/ttyd.h2
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

